### ISSUE TITLE
v4 todo

### ISSUE THREAD

**Issue by bocinsky** [ropensci/FedData#93]
- [ ] `get_ghcn_daily` use `rnoaa` functions throughout
- [x] Remove `data.table` dependency
    - [x] `get_ghcn_daily` 
- [x] Remove `sp` dependency: 
    - [x] `get_ssurgo_inventory`
    - [x] `get_ghcn_inventory`
    - [x] `polygon_from_extent`
    - [x] `spdf_from_polygon`
- [ ] `download_daymet_thredds`: automate tempo code discovery
- [x] Migrate to `terra` for raster output:
    - [x] `get_daymet`
    - [x] `get_nass_cdl`
    - [x] `get_ned`
    - [x] `get_nlcd`
    - [x] `polygon_from_extent`
- [x] Make `rgdal` and `raster` soft dependencies related to returning `raster` objects
    - [x] Utility function for returning `raster` objects
- [ ] Have `get_ssurgo` return spatial data with aggregated map unit data and perhaps VALU1 table

**Comment by maelle** [comment]
@bocinsky Friendly reminder :smile_cat:

**Comment by bocinsky** [comment]
Working on it! Was ready to send to CRAN two days ago, but the NHD map services are struggling. Letting that get sorted before submitting.

**Comment by maelle** [comment]
Thank you! Fingers crossed the services work well again soon!

**Comment by maelle** [comment]
@bocinsky congrats on the successful CRAN update! :tada:
